spring.application.name=gerenciador_de_eventos_api

spring.datasource.url={Url do seu banco de dados}
spring.datasource.username={usuario}
spring.datasource.password={senha}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jackson.deserialization.fail-on-unknown-properties=true

logging.level.org.springframework.security=DEBUG
